  language: python
  python:
    - "3.6"
  install:
    - pip install codecov pytest pytest-cov
    - pip install -r requirements.txt
  script:
    - python -m pytest cov=./ tests/*.py
  after_success:
    - codecov